From bugs+caf_=bugs=bugs.plt-scheme.org@plt-scheme.org Tue Nov 19 11:40:27 2013
Received: from mail-oa0-f41.google.com (mail-oa0-f41.google.com [209.85.219.41])
	by winooski.ccs.neu.edu (8.14.7/8.14.7) with ESMTP id rAJGeQil006634
	for <bugs@bugs.plt-scheme.org>; Tue, 19 Nov 2013 11:40:26 -0500
Message-Id: <201311191640.rAJGeO5Z006625@winooski.ccs.neu.edu>
Date: Tue, 19 Nov 2013 11:40:24 -0500
From: eric.n.dobson@gmail.com
To: bugs@racket-lang.org
Subject: Error messages with wrong function name

>Number:         14179
>Category:       all
>Synopsis:       Error messages with wrong function name
>Class:          sw-bug
>Responsible:    nobody
>Severity:       serious
>Priority:       medium
>State:          open
>Confidential:   no
>Arrival-Date:   Tue Nov 19 11:44:01 -0500 2013
>Originator:     Eric Dobson
>Organization:
plt
>Submitter-Id:   unknown
>Release:        HEAD
>Environment:
MacIntel / Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.28 (KHTML, like Gecko) Chrome/26.0.1397.2 Safari/537.28
>Description:
I expect that a function protected with (case->) would give the same name in error messages regardless of whether or not the underlying function accepts the value.
>How-To-Repeat:
Welcome to Racket v5.90.0.11.
-> (define f (lambda () 1))
-> (define/contract g (case->) f)
-> (procedure-arity f)
0
-> (procedure-arity g)
0
-> (g)
; g: arity mismatch;
;  the expected number of arguments does not match the given number
;   given: 0
; [,bt for context]
-> (g 1)
; f: arity mismatch;
;  the expected number of arguments does not match the given number
;   expected: 0
;   given: 1
; [,bt for context]
-> 
>Fix:
