From nobody@cs.rice.edu  Tue May 11 14:52:03 1999
Received: from web.cs.rice.edu (web.cs.rice.edu [128.42.1.163])
	by cs.rice.edu (8.9.0/8.9.0) with ESMTP id OAA23305
	for <plt-gnats@cs.rice.edu>; Tue, 11 May 1999 14:52:03 -0500 (CDT)
Message-Id: <199905111952.OAA19404@web.cs.rice.edu>
Date: Tue, 11 May 1999 14:52:02 -0500 (CDT)
From: cgodsil@dibbler.uwaterloo.ca
Reply-To: cgodsil@dibbler.uwaterloo.ca
To: plt-gnats@cs.rice.edu
Subject: Getting internal errors when I click on "execute" after invoking continuations 

>Number:         994
>Category:       drscheme
>Synopsis:       Getting internal errors when I click on "execute" after invoking continuations
>Confidential:   no
>Severity:       serious
>Priority:       medium
>Responsible:    robby
>State:          closed
>Class:          sw-bug
>Submitter-Id:   unknown
>Arrival-Date:   Tue May 11 20:00:03 GMT 1999
>Last-Modified:  Tue May 18 09:31:24 MST 1999
>Originator:     Chris Godsil
>Organization:
titan
>Release:        53
>Environment:
Solaris
>Description:
Using drscheme at the r4rs level, I execute the following lines:

(define r #f)
(call/cc
 (lambda (k)
   (set! r k)))
(r 5)
(r 5)

If I now click on the Execute button, two Internal Error windows pop
up, containing the message:
  Internal Error: semaphore-wait: expects argument of type <sema>; 
  given not-yet-cleanup-semaphore
The number of these windows equals the number of times I invoke
the continuation "r".
>How-To-Repeat:
See above
>Fix:

>Audit-Trail:

Responsible-Changed-From-To: steck->robby
Responsible-Changed-By: robby
Responsible-Changed-When: Tue May 18 09:29:35 1999
Responsible-Changed-Why:

State-Changed-From-To: open-closed
State-Changed-By: robby
State-Changed-When: Tue May 18 09:31:16 1999
State-Changed-Why:

fixed in 100alpha2

>Unformatted:
